// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsdhpddjdcaoyhbygfeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZGhwZGRqZGNhb3loYnlnZmVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODE2NDAsImV4cCI6MjA2NjE1NzY0MH0._rhxyzqDZlVQugXS6ueEMNFI8F1EtTF2sHVEix6Zadg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);